language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower
- bower install
script: gulp build
after_success:
- gulp test-coveralls
deploy:
  provider: divshot
  api_key:
    secure: rbL0DnzLO9a17sXanMi7Y+5QHMCOygk4qDZxNKY1qgtlaBKIPH/gh8pp2hJMu8sO9kwKZUqFkB/KNqSyBWK1/kHisltNNMSlkWxUrAb2mVEme0RKvcHQCQHTYflJYfOoSNfIxuv7jC+HdAsUO00ZbYoekt5RmAlwu7mp8hNa0L8=
  skip_cleanup: true
  on:
    repo: randallagordon/qubeulator
notifications:
  webhooks:
    urls:
      secure: "PsHBm4LvecWEQmE0o3oVfwpoh8FNgJESZLik7xg+jTpupsLh9J+LG/oXsgfuwAmTRL3tDVxafZsfpB19iHFiYWcamW3b87nqH3t//Wm8lTSJc0UJurmIYYIwvsXPzT4GRcZl4fTOmp1O20LAajbkIO22UfwmfHdvPJ4ZRbgT2V0="
  slack:
    secure: xZIFg2PcwmndzsmXAf0r7ACE88sQ3/F1/kyX7f56SKGBgX51TLe6pv+btDSHz++PJJdoWX5wY9TWgdYSjbLVSFvfGkUuKKz0AM/X41hpS50JSWfY9cbwSjC4omtOq4N6FGRO2Qxgw+o9Bo+55+JHLdS+UMlVoaXaff0lTsDx7s0=
