language: node_js
node_js:
- '0.10'
install:
- npm i --no-optional
before_script:
- npm install -g bower
- bower install
script: gulp build
deploy:
  provider: divshot
  api_key:
    secure: rbL0DnzLO9a17sXanMi7Y+5QHMCOygk4qDZxNKY1qgtlaBKIPH/gh8pp2hJMu8sO9kwKZUqFkB/KNqSyBWK1/kHisltNNMSlkWxUrAb2mVEme0RKvcHQCQHTYflJYfOoSNfIxuv7jC+HdAsUO00ZbYoekt5RmAlwu7mp8hNa0L8=
  skip_cleanup: true
  on:
    repo: randallagordon/qubeulator
